# Generated by Django 5.1.6 on 2025-02-08 13:25

import phonevalidatorGCC.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonevalidatorGCC.fields.PhoneNumberField(help_text='Enter a valid Egyptian phone number.', max_length=11),
        ),
    ]
