# Generated by Django 5.1.6 on 2025-02-09 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian number (e.g., +201XXXXXXXX or 01XXXXXXXX).', regex='^(\\+20|0)?1[0125]\\d{8}$')]),
        ),
    ]
